name: Publish to Nanos World Store

on:
  push:  # Runs on every push
  workflow_dispatch:  # Allows manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: olivatooo/nanos-world-store-action@main
        with:
          NANOS_PERSONAL_ACCESS_TOKEN: ${{ secrets.NANOS_STORE_TOKEN }}
          NANOS_PACKAGE_NAME: 'turing-test'  # Replace with your package name
          VERBOSE: 'true'
