name: Publish to Nanos World Store

on:
  push:
    tags:
      - 'v*'  # Publishes when you push a version tag
  workflow_dispatch:  # Allows manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: olivatooo/nanos-world-store-action
        with:
          NANOS_PERSONAL_ACCESS_TOKEN: ${{ secrets.NANOS_STORE_TOKEN }}
          NANOS_PACKAGE_NAME: 'testing'  # Replace with your package name
          NANOS_API_URL: 'https://staging.nanos-world.com'
